# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57290bc29e2861a084693f3552fa46f75f5c7ef0fed3e1b7c12dc96d54e1de2e8a7ca87d20459be1198771da47934f960e9ad9a7ce4e40b4c5fe14121c37ae18

test:
  secret_key_base: 039cfaca91359a40e8f708df94c5e1766d7ad7334da56d58013f838d0330897617673959395b26cd45914ddcd807eb350e34475f0e1244bf060f4f7d2d03eb6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
